enum EnumLocal {
  /// TOASTS
  errSomethingWentWrong,
  errEmail,
  errPassword,

  /// STRINGS
  txtAppName,
  txtLogin,
  txtLoginNow,
  txtEnterEmail,
  txtEnterPassword,
  txtEnterConfirmPassword,
  txtForgotPassword,
  txtCreateAccountMsg,
  txtCreateAccount,
  txtEnterFullName,
  txtEnterCompanyName,
  txtForgotPasswordTitle,
  txtSearchHere,
  txtCategories,
  txtSeeAll,
  txtDescription,
  txtSearchYourLocation,
  txtRecentSearch,
  txtPopularCategories,
  txtSearchResult,
  txtAccount,
  txtMyAccount,
  txtViewAndEditProfile,
  txtMyOrders,
  txtSettings,
  txtHelpAndSupport,
  txtLogout,
  txtDeleteAccount,
  txtPickFromPhotos,
  txtPickFromGallery,
  txtPickFromCamera,
}
